export const LOAD_GOOGLE_OAUTH = 'LOAD_GOOGLE_OAUTH2';
export const ON_AUTH_CHANGE = 'ON_AUTH_CHANGE';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// API
export const CREATE_STREAM = 'CREATE_STREAM';
export const GET_STREAMS = 'GET_STREAMS';
export const GET_STREAM = 'GET_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';

// API STATUS
export const STATUS_CREATE_STREAM = 'STATUS_CREATE_STREAM';
export const STATUS_GET_STREAMS = 'STATUS_GET_STREAMS';
export const STATUS_GET_STREAM = 'STATUS_GET_STREAM';
export const STATUS_EDIT_STREAM = 'STATUS_EDIT_STREAM';
export const STATUS_DELETE_STREAM = 'STATUS_DELETE_STREAM';
